INSERT INTO prodotto(categoria_id, nome, descrizione, prezzo, quantita_inventario)
VALUES
(1, "Golden Ceylon",
"Greenfield Golden Ceylon is a premium black tea with a rich, strong flavor and a golden color. This tea is perfect for those who enjoy a bold, invigorating cup.",
1.50, 50),
(1, "Classic Breakfast",
"Greenfield Classic Breakfast is a traditional English breakfast tea that is robust and full-bodied, perfect for starting your day.",
2.30, 40),
(1, "Premium Assam",
"Greenfield Premium Assam is a strong, malty black tea from the Assam region in India, known for its deep, robust flavor.",
2.60, 35),
(1, "Earl Grey",
"Greenfield Earl Grey is a classic black tea flavored with the essence of bergamot, giving it a distinct, fragrant citrus flavor.",
2.70, 35),
(1, "Summer Bouquet",
"Greenfield Summer Bouquet black tea is a delightful blend of black tea and summer fruits, offering a refreshing and fruity flavor.",
3.00, 70),
(1, "Festive Grapes",
"Greenfield Festive Grapes is a unique and refreshing herbal tea that combines the sweetness of dried apples, the mild flavor of rosehip, and the piquant acidity of hibiscus, all softened by the warm aroma of red grapes. This delightful blend creates a full festive flavor that is perfect for any time of the year. \nKey Features: \nHerbal tea blend: A combination of apple, rosehip, and hibiscus creates a unique flavor profile. \nFestive flavor: The warm aroma of red grapes adds a festive touch to this herbal tea. \nCaffeine-free: Perfect for those who want to avoid caffeine or enjoy a relaxing tea at any time of the day. \nKosher: Some products in the Greenfield Festive Grapes range are certified kosher.",
2.20, 50),
(1, "Lemon Spark",
"The deep and full-bodied taste of Greenfield Lemon Spark reveals as wonderful bouquet of Ceylon tea, juicy lemon and pine-scented rosemary in this revival of a traditional recipe. A refreshing citrus blast perfectly complements the delicate natural notes of Ceylon tea to produce enticing and light aroma.",
2.40, 50),
(1, "Grand Fruit",
"Juicy acidity of ripe pomegranate and fresh pine rosemary note bring into this tea bouquet new complex tints highlighting the original bright taste.",
2.50, 20),
(1, "Rose Pineberry",
"Intense black tea with captivating rose aroma and bright pineberry freshness.",
2.60, 30),
(1, "Christmas Mystery",
"Traditional winter drink Christmas Mystery is prepared on the basis of classic black tea. Clove and cinnamon make up spicy bitter notes while citrus rinds give it a refreshing aroma that underlines piquant flavor and festive character of Greenfield Christmas Mystery. Effectively warms up, revitalizes refreshes.",
2.70, 40),
(1, "Silver Fujian",
"Only the youngest tea leaves harvested in early spring are used for the magnificent black tea Greenfield Silver Fujian. Its deep and ripe flavour with exquisite chocolate bitterness and slightly baked notes, a distinguishing feature of the famous teas from Fujian province in China, is perfectly completed with wonderful floral aroma creating an exciting play of shades in the fine bouquet of Silver Fujian.",
2.80, 32),
(1, "Honey Linden",
"Finest bitter and rich notes of buckwheat honey delicately accent astringent tea taste and make the magnificent bouquette complete.",
2.90, 21),
(1, "Barberry Garden",
"Bright and tender flavour of Greenfield Barberry Garden is woven of noble Indian tea power, barberry sour and sweet notes and delicate hibiscus flavour. Light aroma of barberry intertwines with original tea aroma thus producing charming bouquet of Greenfield Barberry Garden.",
2.99, 15);

INSERT INTO prodotto(categoria_id, nome, descrizione, prezzo, quantita_inventario)
VALUES
(2, "Tropical Tarragon",
"Greenfield Tropical Tarragon is a refreshing blend of green tea with tropical tarragon flavor, offering a unique and exotic taste.",
2.50, 11),
(2, "Jasmine Dream",
"Bright jasmine aroma accentuates clean and refreshing flavour profile of the noble green tea from the Chinese province of Yunnan. Spring mood comes with every sip of Jasmine Dream.",
2.30, 20),
(2, "Japanese Sencha",
"Special green tea Japanese Sencha produced accordingly to the Japanese tradition from tealeaves of the first flush perfectly reflects exquisite simplicity and harmony of Japanese culture.",
2.40, 37),
(2, "Milky Oolong",
"Greenfield Milky Oolong has rich pure shades, long-lasting sweet aftertaste completed by delicate notes of capturing creamy flavor.",
2.60, 30),
(2, "Spicy Mango",
"The juicy aroma of ripe mango with hot ginger notes emphasizes the depth and richness of the excellent oolong tea.",
2.70, 22),
(2, "Quince Ginger",
"In the charming composition of Greenfield Quince Ginger delicate astringency of green tea intertwines with hot spiciness of ginger and fine quince notes.",
2.50, 25),
(2, "Mellow Peach",
"Mild composition of Greenfield Mellow Peach is a combination of excellent Chinese tea, natural peach and mandarin peel.",
2.30, 35);

INSERT INTO prodotto(categoria_id, nome, descrizione, prezzo, quantita_inventario)
VALUES
(3, "Cherry Blossom",
"The exciting and alluring flavour of Cherry Blossom brings with it a spectacular interaction of impressions in which ripe cherry echoes a luxurious duet of apple and blackberry. The refreshing sourness of hibiscus highlighted by the mild flavour of rosehip rounds off the blend.",
2.99,25),
(3, "Berry Sunset",
"A marvellous combination of ripe forest fruits — raspberries and blackberries — imparts a unique charm to this natural blend on a base of hibiscus, apple and rosehip. The tantalising sourness of hibiscus brings out the natural apple tones and rounds off the bouquet.",
 2.50,24),
(3, "Camomile Meadow",
"Mild flower flavor in the bouquet of Greenfield Camomile Meadow is brightened with fine notes of fragrant Melissa.",
2.30,30),
(3, "Wildberry Roobois",
"Wildberry Rooibos is an ethnic drink made of young shoots of red bush widespread in South Africa.",
1.99,18),
(3, "Spirit Mate",
"In the bold composition of Greenfield Spirit Mate original rich flavour and invigorating power of the Indian Guarani tribe infusion are combined with slightly bitter yet fresh flavouring of juicy lime.",
1.99,37);
