version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: Teabug
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "teabugs"
      MYSQL_USER: "tea_sommelier"
      MYSQL_PASSWORD: "my_password"
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
